####################################################
# Makefile and file structure generated by cset.sh #
#        Copyright (c) 2025 Artur Twardzik         #
#                                                  #
# Find file on: gist.github.com/atwardzik          #
# File name:    cset.sh                            #
####################################################
.PHONY: all dirs clean

### Toolchain ###
CC := clang

CC_ARGS = -Wall -Wextra -Wpedantic -Werror \
	-Wno-unused-variable -Wno-unused-function -Wno-unused-parameter \
	-std=c23 -O0

### Sources ###
SRCDIR := code
BINDIR := bin

### General ###
all: debug

dirs:
	@mkdir -p $(BINDIR)

clean:
	@rm -rf $(BINDIR)
	@rm -f compile_commands.json

### Binaries ###
debug: $(SRCDIR)/*.c | dirs
	$(CC) $(CC_ARGS) $^ -o $(BINDIR)/debug
